### ISSUE TITLE
Use in browser, not just npm ?

### ISSUE THREAD

**Issue by stuaxo** [zectorio/mesh-gradient-js#1]
It would be great if this could be used in the browser.

Having an API to select which SVGs to modify would be useful here (e.g. pass in some css selector (s)) and have it modify all the SVGs in the page.

**Comment by jay3sh** [comment]
That would be something useful and also trivial to implement. But it doesn't fit into the scope of this project. This project is mainly written for polyfill javascript code. The code that goes inside the SVG and not on top of it. Such code cannot make assumptions about many things because it's embedded inside an SVG. It's not a regular javascript library that is supposed to query and manipulate arbitrary html dom by css selectors. In order for it to work properly it should only query SVG dom. Also it has to be bare minimum because it has to be embedded *inline* inside the SVG.
